from . import hospital_mixin
from . import hospital_patient
from . import hospital_doctor
from . import hospital_disease
from . import hospital_visit
from . import hospital_diagnosis
from . import hospital_doctor_schedule
from . import hospital_history_doctor_change
from . import hospital_analysis
